
CREATE DATABASE Exercicio_1_2__DQL;

CREATE TABLE Empresa 
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE  Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	CPF VARCHAR(11) NOT NULL
)

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Marca VARCHAR(20) NOT NULL
)

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Modelo VARCHAR(20) NOT NULL
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca),
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo),
	Placa VARCHAR(8) NOT NULL
)

CREATE TABLE Aluguel 
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo),
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
	DataInicio VARCHAR(32) NOT NULL,
	DataFim VARCHAR(32) NOT NULL
)