CREATE DATABASE Exercicio_1_3;

CREATE TABLE Clinica
(
		IdClinica INT PRIMARY KEY IDENTITY,
		Endereço VARCHAR(100) NOT NULL
)

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	Nome VARCHAR(50) NOT NULL
)

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL
)

CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	Descrição VARCHAR(50) NOT NULL
)

CREATE TABLE Raça
(
	IdRaça INT PRIMARY KEY IDENTITY,
	Descrição VARCHAR(70)
)

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet),
	IdRaça INT FOREIGN KEY REFERENCES Raça(IdRaça),
	Nome VARCHAR(50),
	DataNascimento VARCHAR(10)
)

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
	DataAtendimento VARCHAR(10),
	Descrição VARCHAR(100)
)