CREATE DATABASE Exercicio_1_4;

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100),
	Email VARCHAR(100)NOT NULL,
	Senha VARCHAR(20)NOT NULL,
	Permissao VARCHAR(50)NOT NULL
)

CREATE TABLE Artista
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50)
)

CREATE TABLE Albuns
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista),
	Titulo VARCHAR(50)NOT NULL,
	DataLançamento VARCHAR(20)NOT NULL,
	Localização VARCHAR(50)NOT NULL,
	QtdMinutos VARCHAR(10)NOT NULL,
	Ativo VARCHAR(20)
)

CREATE TABLE Estilos
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50)
)

CREATE TABLE AlbunsEstilos
(
	IdAlbum INT FOREIGN KEY REFERENCES Albuns(IdAlbum),
	IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo)
)